name: Build and Test

on: 
  # Событие которые запускают jobs
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  # Название job
  Build:
    runs-on: ubuntu-latest
    steps:
      # Actions от github: проверяет репозиторий, гит и т.д.
      - uses: actions/checkout@v3

      # Пример однолинейного простого скрипта shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: List repository
        run: ls -la

      # Пример многолинейного скрипта shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
