name: Build and Test

on: 
  # Событие которые запускают jobs
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  # Название job
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/tests
    steps:
      # Actions от github: проверяет репозиторий, гит и т.д.
      - name: Checout code
        uses: actions/checkout@v4
        
     # - name: Setup Java JDK  
     #   uses: actions/setup-java@v4.2.2
     #   with: 
      #    java-version: '21'
       #   distribution: 'temurin'

     # - name: Setup Gradle
    #    uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
     #   with:
     #     gradle-version: '8.7'

     # - name: Check Java Verion
     #   run: java --version
        
     # - name: Check Gradle version
      #  run: gradle -v
        
      #- name: Build with Gradle Wrapper
      #  run: |
      #    cd ./app ; ./gradlew build

      - name: Where am I
        run: pwd

      - name: Run make
        run: make say-hello
      - name: Print Secret
        run: echo "${{ secrets.SECRET_PRINT}}"
          
