name: Build and Test

on: 
  # Событие которые запускают jobs
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  # Название job
  Build:
    runs-on: ubuntu-latest
    steps:
      # Actions от github: проверяет репозиторий, гит и т.д.
      - name: Checout code
        uses: actions/checkout@v4
        
      - name: Setup Java JDK  
        uses: actions/setup-java@v4.2.2
        with: 
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: '8.7'

      - name: Check repository
        run: |
          cd ./app
          ls -la
          ./gradlew build
          ./gradlew  test
          
