name: Build and Test

on: 
  # Событие которые запускают jobs
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  # Название job
  Build:
    runs-on: ubuntu-latest
    steps:
      # Actions от github: проверяет репозиторий, гит и т.д.
      - name: Checout code
        uses: actions/checkout@v4
        
      - name: Setup Java JDK  
        uses: actions/setup-java@v4.2.2
        with: 
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
          
      # Пример однолинейного простого скрипта shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: List repository
        run: ls -la

      # Пример многолинейного скрипта shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Check repository
        run: |
          cd ./app
          ls -la
          make build
          make test
          make run-project:
          
